import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { useTranslation } from 'react-i18next'
import { ROUTES } from '../utils/constants'
import './projects.css'
import PageCinematicHero from '../components/PageCinematicHero'

export const PROJECT_IMAGES = ['/images/WhatsApp Image 2025-12-05 at 3.40.02 PM.jpeg','/images/WhatsApp Image 2025-12-05 at 3.40.03 PM1.jpeg','/images/WhatsApp Image 2025-12-05 at 3.40.04 PM2.jpeg','/images/WhatsApp Image 2025-12-05 at 3.40.05 PM4.jpeg','/images/WhatsApp Image 2025-12-05 at 3.40.07 PM7.jpeg','/images/WhatsApp Image 2025-12-05 at 3.40.08 PM3.jpeg','/images/WhatsApp Image 2025-12-05 at 3.40.08 PM6.jpeg','/images/WhatsApp Image 2025-12-05 at 3.40.08 PM9.jpeg']
export const PROJECTS={ar:[['منظومة ري زراعية بالطاقة الشمسية','الرياض','180 ك.و','نظام شمسي لتشغيل مضخات الري وتقليل الاعتماد على مولدات الوقود في مزرعة متوسطة المساحة.'],['محطة مصنع أغذية','الخرج','420 ك.و','منظومة متصلة بالشبكة تغطي جزءًا كبيرًا من حمل المصنع النهاري وتدعم خفض تكلفة التشغيل.'],['مستودعات تبريد زراعية','القصيم','260 ك.و','حل مصمم لأحمال التبريد المستمرة مع مراقبة ذكية للإنتاج والاستهلاك.'],['مجمع تجاري','جدة','310 ك.و','ألواح عالية الكفاءة فوق مواقف السيارات لتوليد الطاقة وتوفير الظل للزوار.'],['مزرعة دواجن','حائل','150 ك.و','منظومة هجينة تدعم التهوية والتبريد مع بطاريات للحفاظ على الأحمال الأساسية.'],['محطة ضخ مياه','المدينة المنورة','95 ك.و','تشغيل مضخات المياه نهارًا بالطاقة الشمسية مع تحكم مخصص لاحتياج الموقع.'],['ورشة صناعية','الدمام','225 ك.و','منظومة أسطح متصلة بالشبكة مصممة لتحمل الظروف المناخية وتقليل فاتورة الكهرباء.'],['منتجع صحراوي','تبوك','135 ك.و','حل هجين يجمع الطاقة الشمسية والتخزين لتوفير طاقة مستقرة في موقع بعيد.']],en:[['Solar Irrigation System','Riyadh','180 kW','A solar system designed to operate irrigation pumps and reduce generator dependence for a medium-sized farm.'],['Food Factory Solar Plant','Al Kharj','420 kW','A grid-tied system covering a substantial share of daytime factory demand and reducing operating costs.'],['Agricultural Cold Storage','Qassim','260 kW','A solution designed for continuous cooling loads with smart production and consumption monitoring.'],['Commercial Complex','Jeddah','310 kW','High-efficiency panels installed over parking spaces to generate power while providing visitor shade.'],['Poultry Farm','Hail','150 kW','A hybrid system supporting ventilation and cooling, with batteries for essential loads.'],['Water Pumping Station','Madinah','95 kW','Daytime solar operation for water pumps with controls tailored to the site requirements.'],['Industrial Workshop','Dammam','225 kW','A grid-tied rooftop system engineered for local climate conditions and lower electricity bills.'],['Desert Resort','Tabuk','135 kW','A hybrid solar and storage solution providing stable energy for a remote site.']]}
export default function Projects(){const {i18n}=useTranslation();const ar=i18n.language==='ar';const projects=PROJECTS[ar?'ar':'en'];return <main className="projects-page"><PageCinematicHero eyebrow={ar?'مجموعة مختارة من مشاريعنا':'A selection of our projects'} title={ar?'مشاريع طاقة مصممة لكل قطاع':'Solar projects designed for every sector'} subtitle={ar?'المشاريع المعروضة هنا جزء من مشاريعنا ولا تمثل جميع المشاريع التي نفذناها.':'The projects shown here are a selection of our work and do not represent every project we have delivered.'} primaryLabel={ar?'ابدأ مشروعك':'Start your project'} primaryTo={ROUTES.contact} secondaryLabel={ar?'خدماتنا':'Our services'} secondaryTo={ROUTES.services} /><section className="projects-grid">{projects.map(([title,location,capacity,description],index)=><motion.article key={title} initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{duration:.5,delay:(index%3)*.08}}><Link to={`/projects/${index+1}`} className="projects-card__image"><img src={PROJECT_IMAGES[index]} alt={title} loading="lazy"/><span>{String(index+1).padStart(2,'0')}</span></Link><div className="projects-card__body"><div><small>{location}</small><b>{capacity}</b></div><h2><Link to={`/projects/${index+1}`}>{title}</Link></h2><p>{description}</p><Link to={ROUTES.contact}>{ar?'ناقش مشروعًا مشابهًا':'Discuss a similar project'} <i>{ar?'←':'→'}</i></Link></div></motion.article>)}</section><section className="projects-cta"><p>{ar?'هل لديك موقع أو حمل كهربائي تريد دراسته؟':'Have a site or electrical load you want us to assess?'}</p><Link to={ROUTES.contact}>{ar?'ابدأ مشروعك معنا':'Start your project'}</Link></section></main>}



